name: Kodi
on:
- pull_request
- push
jobs:
  tests:
    name: Addon checker
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kodi-branch: [matrix, nexus, omega]
    steps:
    - uses: actions/checkout@v2
      with:
        path: ${{ github.repository }}
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libxml2-utils xmlstarlet
        python -m pip install --upgrade pip packaging
        pip install kodi-addon-checker
    - name: Remove unwanted files
      run: awk '/export-ignore/ { print $1 }' .gitattributes | xargs rm -rf --
      working-directory: ${{ github.repository }}
    - name: Run kodi-addon-checker
      run: kodi-addon-checker --branch=${{ matrix.kodi-branch }} ${{ github.repository }}/
